list1 <- list(
  #"KYTX" = list("name" = "Kyverna Therapeutics, Inc.", "src" = "yahoo")
  #, "22UA.DE" = list("name" = "BioNTech SE", "src" = "yahoo")
  "AFX.DE" = list("name" = "Carl Zeiss Meditec AG", "src" = "yahoo", "isin" = "DE0005313704")
  #, "ASME.DE" = list("name" = "ASML Holding N.V.", "src" = "yahoo", "isin" = "NL0010273215")
  , "CPA.DE" = list("name" = "Colgate-Palmolive Company", "src" = "yahoo")
  , "HEI.DE" = list("name" = "HeidelbergCement AG", "src" = "yahoo")
  #, "IFX.DE" = list("name" = "Infineon Technologies AG", "src" = "yahoo")
  #, "KHNZ.DE" = list("name" = "The Kraft Heinz Company", "src" = "yahoo")
  #, "MSGL.HM" = list("name" = "msg life ag", "src" = "yahoo")
  , "MBG.DE" = list("name" = "Mercedes-Benz Group AG", "src" = "yahoo", "isin" = "DE0007100000")
  #, "P911.DE" = list("name" = "Dr. Ing. h.c. F. Porsche AG", "src" = "yahoo", "isin" = "DE000PAG9113")
  #, "QBY.DE" = list("name" = "q.beyond AG", "src" = "yahoo", "isin" = "DE0005137004")
  , "IVV" = list("name" = "iShares Core S&P 500 ETF", "src" = "yahoo", "isin" = "IE00B5BMR087")
  , "TLT" = list("name" = "iShares 20+ Year Treasury Bond ETF", "src" = "yahoo")
  , "SIX3.DE" = list("name" = "Sixt SE", "src" = "yahoo")
  , "FR.PA" = list("name" = "Valeo SE", "src" = "yahoo")
  , "VIB3.DE" = list("name" = "Villeroy & Boch AG", "src" = "yahoo")
  , "WCH.DE" = list("name" = "Wacker Chemie AG", "src" = "yahoo")
)

list2 <- list(
  "XDWD.DE" = list("name" = "Xtrackers MSCI World UCITS ETF", "src" = "yahoo", "isin" = "IE00BJ0KDQ92")
  , "XMAW.DE" = list("name" = "Xtrackers MSCI AC World ESG Screened UCITS ETF", "src" = "yahoo", "isin" = "IE00BGHQ0G80")
  , "EXS2.DE" = list("name" = "iShares TecDAX UCITS ETF (DE)", "src" = "yahoo", "isin" = "DE0005933972")
  , "ESIH.DE" = list("name" = "iShares MSCI Europe Health Care Sector UCITS ETF", "src" = "yahoo", "isin" = "IE00BMW42181")
  #, "DXSE.DE" = list("name" = "Xtrackers MSCI Europe Health Care ESG Screened UCITS ETF", "src" = "yahoo", "isin" = "LU0292103222")
  , "XSX6.DE" = list("name" = "Xtrackers Stoxx Europe 600 UCITS ETF", "src" = "yahoo", "isin" = "LU0328475792")
  , "DX2J.SG" = list("name" = "Xtrackers MSCI Europe Small Cap UCITS ETF", "src" = "yahoo", "isin" = "LU0322253906")
  , "INRG.MI" = list("name" = "iShares Global Clean Energy UCITS ETF USD (Dist)", "src" = "yahoo", "isin" = "IE00B1XNHC34")
  , "XDWS.DE" = list("name" = "Xtrackers MSCI World Consumer Staples UCITS ETF", "src" = "yahoo", "isin" = "IE00BM67HN09")
  #, "XZEU.DE" = list("name" = "Xtrackers MSCI Europe ESG UCITS ETF", "src" = "yahoo", "isin" = "IE00BFMNHK08")
  #, "DBXJ.DE" = list("name" = "Xtrackers MSCI Japan UCITS ETF", "src" = "yahoo", "isin" = "LU0274209740")
  #, "IS0D.DE" = list("name" = "iShares Oil & Gas Exploration & Production UCITS ETF USD (Acc)", "src" = "yahoo", "isin" = "IE00B6R51Z18")
  , "0MLC.IL" = list("name" = "iShares STOXX Europe Select Dividend 30 UCITS ETF (DE)", "src" = "yahoo", "isin" = "DE0002635299")
  , "IS0E.DE" = list("name" = "iShares V PLC iShares Gold Producers UCITS ETF USD (Acc)", "src" = "yahoo", "isin" = "IE00B6R52036")
  , "ISPA.DE" = list("name" = "iShares STOXX Global Select Dividend 100 UCITS ETF (DE)", "src" = "yahoo", "isin" = "DE000A0F5UH1")
  , "EXS3.DE" = list("name" = "iShares MDAX UCITS ETF", "src" = "yahoo", "isin" = "DE0005933923")
  , "DBXG.DE" = list("name" = "Xtrackers II Eurozone Government Bond 25+ UCITS ETF 1C", "src" = "yahoo", "isin" = "LU0290357846")
  , "IMR.F" = list("name" = "AC Immune", "src" = "yahoo", "isin" = "CH0329023102")
  #, "BST.DE" = list("name" = "Bastei Lübbe AG", "src" = "yahoo", "isin" = "DE000A1X3YY0")
  , "1F6.F" = list("name" = "Fermentalg SA", "src" = "yahoo", "isin" = "FR0011271600")
  , "NCH2.DE" = list("name" = "thyssenkrupp nucera AG & Co. KGaA", "src" = "yahoo", "isin" = "DE000NCA0001")
  , "NJB.F" = list("name" = "NIBE Industrier AB (publ)", "src" = "yahoo", "isin" = "SE0015988019")
  , "4R0.F" = list("name" = "Oxford Nanopore Technologies plc", "src" = "yahoo", "isin" = "GB00BP6S8Z30")
  #, "AMD.F" = list("name" = "Advanced Micro Devices, Inc.", "src" = "yahoo", "isin" = "US0079031078")
  , "ACT.DE" = list("name" = "AlzChem Group AG", "src" = "yahoo", "isin" = "DE000A2YNT30")
  #, "NDA.DE" = list("name" = "Aurubis AG", "src" = "yahoo", "isin" = "DE0006766504")
  #, "BAYN.DE" = list("name" = "Bayer Aktiengesellschaft", "src" = "yahoo", "isin" = "DE000BAY0017")
  , "BMW.DE" = list("name" = "Bayerische Motoren Werke AG", "src" = "yahoo", "isin" = "DE0005190037")
  , "BRYN.DE" = list("name" = "Berkshire Hathaway Inc.", "src" = "yahoo", "isin" = "US0846707026")
  , "CAT1.DE" = list("name" = "Caterpillar Inc.", "src" = "yahoo", "isin" = "US1491231015")
  #, "D6H.DE" = list("name" = "DATAGROUP SE", "src" = "yahoo", "isin" = "DE000A0JC8S7")
  , "DRW3.DE" = list("name" = "Drägerwerk AG & Co. KGaA", "src" = "yahoo", "isin" = "DE0005550636")
  , "HXCK.DE" = list("name" = "Ernst Russ AG", "src" = "yahoo", "isin" = "DE000A161077")
  #, "ELG.DE" = list("name" = "Elmos Semiconductor SE", "src" = "yahoo", "isin" = "DE0005677108")
  #, "HLAG.DE" = list("name" = "Hapag-Lloyd Aktiengesellschaft", "src" = "yahoo", "isin" = "DE000HLAG475")
  , "KTA.DE" = list("name" = "Knaus Tabbert AG", "src" = "yahoo", "isin" = "DE000A2YN504")
  #, "LAR0.F" = list("name" = "Lam Research Corporation", "src" = "yahoo", "isin" = "US5128073062")
  , "MOH.DE" = list("name" = "LVMH Moet Hennessy", "src" = "yahoo", "isin" = "FR0000121014")
  , "MDO.DE" = list("name" = "McDonald's Corporation", "src" = "yahoo", "isin" = "US5801351017")
  , "MPCK.DE" = list("name" = "MPC Münchmeyer Petersen Capital AG", "src" = "yahoo", "isin" = "DE000A1TNWJ4")
  , "NVD.DE" = list("name" = "NVIDIA Corporation", "src" = "yahoo", "isin" = "US67066G1040")
  , "PYPL" = list("name" = "PayPal Holdings, Inc.", "src" = "yahoo", "isin" = "US70450Y1038")
  , "SHL.DE" = list("name" = "Siemens Healthineers AG", "src" = "yahoo", "isin" = "DE000SHL1006")
  , "SZU.DE" = list("name" = "Südzucker AG", "src" = "yahoo", "isin" = "DE0007297004")
  , "PAH3.DE" = list("name" = "Porsche Automobil Holding SE", "src" = "yahoo", "isin" = "DE000PAH0038")
  #, "ZAL.DE" = list("name" = "Zalando SE", "src" = "yahoo", "isin" = "DE000ZAL1111")
  , "R3NK.DE" = list("name" = "RENK Group AG", "src" = "yahoo", "isin" = "DE000RENK730")
  , "VOW3.DE" = list("name" = "Volkswagen Vz", "src" = "yahoo", "isin" = "DE0007664039")
  #, "WAF.DE" = list("name" = "Siltronic AG", "src" = "yahoo", "isin" = "DE000WAF3001")
  #, "ADA-EUR" = list("name" = "Cardano EUR", "src" = "yahoo")
)

list3 <- list(
  "^GDAXI" = list("name" = "DAX Performance Index", "src" = "yahoo")
  , "^GDAXIP" = list("name" = "DAX KURSINDEX", "src" = "yahoo")
  , "^MDAXI" = list("name" = "MDAX", "src" = "yahoo")
  , "^GSPC" = list("name" = "S&P 500", "src" = "yahoo")
  , "^SPXEW" = list("name" = "S&P EQUAL WEIGHT INDEX", "src" = "yahoo")
  , "^DJI" = list("name" = "Dow Jones Industrial Average", "src" = "yahoo")
  , "^IXIC" = list("name" = "Nasdaq Composite", "src" = "yahoo")
  , "DGS10" = list("name" = " Market Yield on U.S. Treasury Securities at 10-Year Constant Maturity", "src" = "FRED")
  , "GC=F" = list("name" = "Gold", "src" = "yahoo")
  , "EURUSD=X" = list("name" = "EUR/USD", "src" = "yahoo")
  , "CL=F" = list("name" = "Crude Oil", "src" = "yahoo")
)
