list1 <- list(
  #"KYTX" = list("name" = "Kyverna Therapeutics, Inc.", "src" = "yahoo")
  "ACT.DE" = list("name" = "AlzChem Group AG", "src" = "yahoo")
  , "22UA.DE" = list("name" = "BioNTech SE", "src" = "yahoo")
  , "BAYN.DE" = list("name" = "Bayer Aktiengesellschaft", "src" = "yahoo")
  , "CPA.DE" = list("name" = "Colgate-Palmolive Company", "src" = "yahoo")
  , "HLAG.DE" = list("name" = "Hapag-Lloyd Aktiengesellschaft", "src" = "yahoo")
  , "HEI.DE" = list("name" = "HeidelbergCement AG", "src" = "yahoo")
  , "IFX.DE" = list("name" = "Infineon Technologies AG", "src" = "yahoo")
  , "MSGL.HM" = list("name" = "msg life ag", "src" = "yahoo")
  , "MBG.DE" = list("name" = "Mercedes-Benz Group AG", "src" = "yahoo")
  , "SIX3.DE" = list("name" = "Sixt SE", "src" = "yahoo")
)

list2 <- list(
  "XDWD.DE" = list("name" = "Xtrackers MSCI World UCITS ETF", "src" = "yahoo")
  , "XMAW.DE" = list("name" = "Xtrackers MSCI AC World ESG Screened UCITS ETF", "src" = "yahoo")
  , "IVV" = list("name" = "iShares Core S&P 500 ETF", "src" = "yahoo")
  , "EXS2.DE" = list("name" = "iShares TecDAX UCITS ETF (DE)", "src" = "yahoo")
  , "ESIH.DE" = list("name" = "iShares MSCI Europe Health Care Sector UCITS ETF", "src" = "yahoo")
  #, "DXSE.DE" = list("name" = "Xtrackers MSCI Europe Health Care ESG Screened UCITS ETF", "src" = "yahoo")
  , "XSX6.DE" = list("name" = "Xtrackers Stoxx Europe 600 UCITS ETF", "src" = "yahoo")
  , "DX2J.SG" = list("name" = "Xtrackers MSCI Europe Small Cap UCITS ETF", "src" = "yahoo")
  , "INRG.MI" = list("name" = "iShares Global Clean Energy UCITS ETF USD (Dist)", "src" = "yahoo")
  , "XDWS.DE" = list("name" = "Xtrackers MSCI World Consumer Staples UCITS ETF", "src" = "yahoo")
  #, "XZEU.DE" = list("name" = "Xtrackers MSCI Europe ESG UCITS ETF", "src" = "yahoo")
  #, "DBXJ.DE" = list("name" = "Xtrackers MSCI Japan UCITS ETF", "src" = "yahoo")
  , "IS0D.DE" = list("name" = "iShares Oil & Gas Exploration & Production UCITS ETF USD (Acc)", "src" = "yahoo")
  , "0MLC.IL" = list("name" = "iShares STOXX Europe Select Dividend 30 UCITS ETF (DE)", "src" = "yahoo")
  , "IS0E.DE" = list("name" = "iShares V PLC iShares Gold Producers UCITS ETF USD (Acc)", "src" = "yahoo")
  , "ISPA.DE" = list("name" = "iShares STOXX Global Select Dividend 100 UCITS ETF (DE)", "src" = "yahoo")
  , "DBXG.DE" = list("name" = "Xtrackers II Eurozone Government Bond 25+ UCITS ETF 1C", "src" = "yahoo")
  , "IMR.F" = list("name" = "AC Immune", "src" = "yahoo")
  , "BST.DE" = list("name" = "Bastei Lübbe AG", "src" = "yahoo")
  , "1F6.F" = list("name" = "Fermentalg SA", "src" = "yahoo")
  , "NCH2.DE" = list("name" = "thyssenkrupp nucera AG & Co. KGaA", "src" = "yahoo")
  , "NJB.F" = list("name" = "NIBE Industrier AB (publ)", "src" = "yahoo")
  , "4R0.F" = list("name" = "Oxford Nanopore Technologies plc", "src" = "yahoo")
  , "QBY.DE" = list("name" = "q.beyond AG", "src" = "yahoo")
  , "AMD.F" = list("name" = "Advanced Micro Devices, Inc.", "src" = "yahoo")
  , "NDA.DE" = list("name" = "Aurubis AG", "src" = "yahoo")
  , "AFX.DE" = list("name" = "Carl Zeiss Meditec AG", "src" = "yahoo")
  , "D6H.DE" = list("name" = "DATAGROUP SE", "src" = "yahoo")
  , "DRW3.DE" = list("name" = "Drägerwerk AG & Co. KGaA", "src" = "yahoo")
  , "HXCK.DE" = list("name" = "Ernst Russ AG", "src" = "yahoo")
  , "ELG.DE" = list("name" = "Elmos Semiconductor SE", "src" = "yahoo")
  , "KTA.DE" = list("name" = "Knaus Tabbert AG", "src" = "yahoo")
  , "KHNZ.DE" = list("name" = "The Kraft Heinz Company", "src" = "yahoo")
  , "MOH.DE" = list("name" = "LVMH Moet Hennessy", "src" = "yahoo")
  , "MPCK.DE" = list("name" = "MPC Münchmeyer Petersen Capital AG", "src" = "yahoo")
  , "NVD.DE" = list("name" = "NVIDIA Corporation", "src" = "yahoo")
  , "PYPL" = list("name" = "PayPal Holdings, Inc.", "src" = "yahoo")
  , "SHL.DE" = list("name" = "Siemens Healthineers AG", "src" = "yahoo")
  , "SZU.DE" = list("name" = "Südzucker AG", "src" = "yahoo")
  , "PAH3.DE" = list("name" = "Porsche Automobil Holding SE", "src" = "yahoo")
  #, "ZAL.DE" = list("name" = "Zalando SE", "src" = "yahoo")
  , "P911.DE" = list("name" = "Dr. Ing. h.c. F. Porsche AG", "src" = "yahoo")
  , "VIB3.DE" = list("name" = "Villeroy & Boch AG", "src" = "yahoo")
  , "VOW3.DE" = list("name" = "Volkswagen Vz", "src" = "yahoo")
  , "WAF.DE" = list("name" = "Siltronic AG", "src" = "yahoo")
  , "WCH.DE" = list("name" = "Wacker Chemie AG", "src" = "yahoo")
  , "ADA-EUR" = list("name" = "Cardano EUR", "src" = "yahoo")
)

list3 <- list(
  "^GDAXI" = list("name" = "DAX Performance Index", "src" = "yahoo")
  , "^GDAXIP" = list("name" = "DAX KURSINDEX", "src" = "yahoo")
  , "^GSPC" = list("name" = "S&P 500", "src" = "yahoo")
  , "^SPXEW" = list("name" = "S&P EQUAL WEIGHT INDEX", "src" = "yahoo")
  , "^DJI" = list("name" = "Dow Jones Industrial Average", "src" = "yahoo")
  , "^IXIC" = list("name" = "Nasdaq Composite", "src" = "yahoo")
  , "DGS10" = list("name" = " Market Yield on U.S. Treasury Securities at 10-Year Constant Maturity", "src" = "FRED")
  , "GC=F" = list("name" = "Gold", "src" = "yahoo")
  , "EURUSD=X" = list("name" = "EUR/USD", "src" = "yahoo")
  , "CL=F" = list("name" = "Crude Oil", "src" = "yahoo")
)
