list1 <- list(
  #"KYTX" = "Kyverna Therapeutics, Inc."
  "ACT.DE" = "AlzChem Group AG"
  , "BST.DE" = "Bastei Lübbe AG"
  , "22UA.DE" = "BioNTech SE"
  , "CPA.DE" = "Colgate-Palmolive Company"
  , "D6H.DE" = "DATAGROUP SE"
  , "HEI.DE" = "HeidelbergCement AG"
  , "IFX.DE" = "Infineon Technologies AG"
  , "MSGL.HM" = "msg life ag"
  , "QBY.DE" = "q.beyond AG"
  , "VIB3.DE" = "Villeroy & Boch AG"
  , "P911.DE" = "Dr. Ing. h.c. F. Porsche AG"
  , "VOW3.DE" = "Volkswagen Vz"
  , "MBG.DE" = "Mercedes-Benz Group AG"
)

list2 <- list(
  "XDWD.DE" = "Xtrackers MSCI World UCITS ETF"
  , "XMAW.DE" = "Xtrackers MSCI AC World ESG Screened UCITS ETF"
  , "IVV" = "iShares Core S&P 500 ETF"
  , "EXS2.DE" = "iShares TecDAX UCITS ETF (DE)"
  , "ESIH.DE" = "iShares MSCI Europe Health Care Sector UCITS ETF"
  #, "DXSE.DE" = "Xtrackers MSCI Europe Health Care ESG Screened UCITS ETF"
  , "XSX6.DE" = "Xtrackers Stoxx Europe 600 UCITS ETF"
  , "DX2J.SG" = "Xtrackers MSCI Europe Small Cap UCITS ETF"
  , "INRG.MI" = "iShares Global Clean Energy UCITS ETF USD (Dist)"
  , "XDWS.DE" = "Xtrackers MSCI World Consumer Staples UCITS ETF"
  #, "XZEU.DE" = "Xtrackers MSCI Europe ESG UCITS ETF"
  #, "DBXJ.DE" = "Xtrackers MSCI Japan UCITS ETF"
  , "IS0D.DE" = "iShares Oil & Gas Exploration & Production UCITS ETF USD (Acc)"
  , "0MLC.IL" = "iShares STOXX Europe Select Dividend 30 UCITS ETF (DE)"
  , "IS0E.DE" = "iShares V PLC iShares Gold Producers UCITS ETF USD (Acc)"
  , "ISPA.DE" = "iShares STOXX Global Select Dividend 100 UCITS ETF (DE)"
  , "DBXG.DE" = "Xtrackers II Eurozone Government Bond 25+ UCITS ETF 1C"
  , "IMR.F" = "AC Immune"
  , "1F6.F" = "Fermentalg SA"
  , "NCH2.DE" = "thyssenkrupp nucera AG & Co. KGaA"
  , "NJB.F" = "NIBE Industrier AB (publ)"
  , "4R0.F" = "Oxford Nanopore Technologies plc"
  , "AMD.F" = "Advanced Micro Devices, Inc."
  , "NDA.DE" = "Aurubis AG"
  , "DRW3.DE" = "Drägerwerk AG & Co. KGaA"
  , "HXCK.DE" = "Ernst Russ AG"
  , "ELG.DE" = "Elmos Semiconductor SE"
  , "KTA.DE" = "Knaus Tabbert AG"
  , "MOH.DE" = "LVMH Moet Hennessy"
  , "MPCK.DE" = "MPC Münchmeyer Petersen Capital AG"
  , "NVD.DE" = "NVIDIA Corporation"
  #, "HLAG.DE" = "Hapag-Lloyd Aktiengesellschaft"
  , "PYPL" = "PayPal Holdings, Inc."
  , "SHL.DE" = "Siemens Healthineers AG"
  , "SZU.DE" = "Südzucker AG"
  , "PAH3.DE" = "Porsche Automobil Holding SE"
  #, "ZAL.DE" = "Zalando SE"
  , "ADA-EUR" = "Cardano EUR"
)

list3 <- list(
  "^GDAXI" = "DAX Performance Index"
  , "^GDAXIP" = "DAX KURSINDEX"
  , "^GSPC" = "S&P 500"
  , "^SPXEW" = "S&P EQUAL WEIGHT INDEX"
  , "^DJI" = "Dow Jones Industrial Average"
  , "^IXIC" = "Nasdaq Composite"
  , "GC=F" = "Gold"
  , "EURUSD=X" = "EUR/USD"
  , "CL=F" = "Crude Oil"
)
