list1 <- list(
  "VOL4.F" = "AB Volvo (publ)"
  , "ACT.DE" = "AlzChem Group AG"
  , "22UA.DE" = "BioNTech SE"
  , "CNTG" = "Centogene N.V."
  , "CPA.DE" = "Colgate-Palmolive Company"
  , "DRW3.DE" = "Drägerwerk AG & Co. KGaA"
  , "FALG.PA" = "Fermentalg SA"
  , "HEI.DE" = "HeidelbergCement AG"
  , "IFX.DE" = "Infineon Technologies AG"
  , "KTA.DE" = "Knaus Tabbert AG"
  , "MAT1.F" = "Panasonic Holdings Corp"
  , "S9I.F" = "Stemmer Imaging AG"
  , "PAH3.DE" = "Porsche Automobil Holding SE"
  , "VOW3.DE" = "Volkswagen Vz"
  , "MBG.DE" = "Mercedes-Benz Group AG"
)

list2 <- list(
  "XDWD.DE" = "Xtrackers MSCI World UCITS ETF"
  , "XMAW.DE" = "Xtrackers MSCI AC World ESG Screened UCITS ETF"
  , "IVV" = "iShares Core S&P 500 ETF"
  , "EXS2.DE" = "iShares TecDAX UCITS ETF (DE)"
  , "ESIH.DE" = "iShares MSCI Europe Health Care Sector UCITS ETF"
  , "DXSE.DE" = "Xtrackers MSCI Europe Health Care ESG Screened UCITS ETF"
  , "XSX6.DE" = "Xtrackers Stoxx Europe 600 UCITS ETF"
  , "DX2J.SG" = "Xtrackers MSCI Europe Small Cap UCITS ETF"
  , "INRG.MI" = "iShares Global Clean Energy UCITS ETF USD (Dist)"
  , "XDWS.DE" = "Xtrackers MSCI World Consumer Staples UCITS ETF"
  , "XZEU.DE" = "Xtrackers MSCI Europe ESG UCITS ETF"
  , "DBXJ.DE" = "Xtrackers MSCI Japan UCITS ETF"
  , "SHL.DE" = "Siemens Healthineers AG"
  , "IMR.F" = "AC Immune"
  , "AMD.F" = "Advanced Micro Devices, Inc."
  , "ELG.DE" = "Elmos Semiconductor SE"
  , "NJB.F" = "NIBE Industrier AB (publ)"
  #, "NCH2.DE" = "thyssenkrupp nucera AG & Co. KGaA"
  , "ADA-EUR" = "Cardano EUR"
)
